# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tulo/employees/v1/employee.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tulo/employees/v1/employee.proto", :syntax => :proto3) do
    add_message "tulo.employees.v1.EmployeesResponse" do
      repeated :employees, :message, 1, "tulo.employees.v1.Employee"
    end
    add_message "tulo.employees.v1.UpsertEmployeeRequest" do
      optional :employee, :message, 1, "tulo.employees.v1.Employee"
    end
    add_message "tulo.employees.v1.UpsertEmployeeResponse" do
      optional :employee, :message, 1, "tulo.employees.v1.Employee"
    end
    add_message "tulo.employees.v1.Employee" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
      optional :first_name, :message, 2, "google.protobuf.StringValue"
      optional :last_name, :message, 3, "google.protobuf.StringValue"
      optional :gender, :message, 4, "google.protobuf.StringValue"
      optional :dob, :message, 5, "google.protobuf.StringValue"
      optional :email, :message, 6, "google.protobuf.StringValue"
      optional :phone, :message, 7, "google.protobuf.StringValue"
      optional :master_country_id, :message, 8, "google.protobuf.Int64Value"
      optional :master_province_id, :message, 9, "google.protobuf.Int64Value"
      optional :master_district_id, :message, 10, "google.protobuf.Int64Value"
      optional :master_ward_id, :message, 11, "google.protobuf.Int64Value"
      optional :owner_id, :message, 12, "google.protobuf.Int64Value"
      optional :department_id, :message, 13, "google.protobuf.Int64Value"
      optional :role_id, :message, 14, "google.protobuf.Int64Value"
      optional :created_at, :message, 15, "google.protobuf.StringValue"
      optional :updated_at, :message, 116, "google.protobuf.StringValue"
    end
  end
end

module Tulo
  module Employees
    module V1
      EmployeesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.employees.v1.EmployeesResponse").msgclass
      UpsertEmployeeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.employees.v1.UpsertEmployeeRequest").msgclass
      UpsertEmployeeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.employees.v1.UpsertEmployeeResponse").msgclass
      Employee = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.employees.v1.Employee").msgclass
    end
  end
end
