# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tulo/common/v1/user.proto for package 'tulo.common.v1'

require 'grpc'
require 'tulo/common/v1/user_pb'

module Tulo
  module Common
    module V1
      module UserService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tulo.common.v1.UserService'

          # --
          # common_005 Get Users
          # --
          rpc :GetUsers, ::Google::Protobuf::Empty, ::Tulo::Common::V1::UsersResponse
          # --
          # common_006 Upsert User
          # --
          rpc :UpsertUser, ::Tulo::Common::V1::UpsertUserRequest, ::Tulo::Common::V1::UpsertUserResponse
          # --
          # common_007 User Login
          # --
          rpc :UserLogin, ::Tulo::Common::V1::LoginInfoRequest, ::Tulo::Common::V1::UserResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
